greet:
  word: 嗨

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

# 配置端口
server:
  port: 8080

greeting:
  name: ss

---
# 开发配置
spring:
  profiles: dev

greeting:
  name: sylvan


---
# 生产配置
spring:
  profiles: prod

greeting:
  name: sisi
